name: Labeling_workflow
on:
issues:
types: [opened, edited, reopened]
jobs:
label_issues:
runs-on: ubunto-latest
steps:
-uses: actions/checkout@v1
-name: Print Hello world
run: eco Hello world!
-name: label-step
uses: ./.github/actions/issuelaber
with:
repo-token: ${{secrets.GITHUB_TOKEN}}
